### ISSUE TITLE
There is an assumption that a zip is being downloaded for all Helm platforms

### ISSUE THREAD

**Issue by hoshposh** [deviceinsight/helm-maven-plugin#57]
Running on a mac an attempt is made to download the following artifact, `https://kubernetes-helm.storage.googleapis.com/helm-v3.3.1-darwin-amd64.zip`, when for OS-X and Linux the extension is a `.tar.gz` and should be `https://kubernetes-helm.storage.googleapis.com/helm-v3.3.1-darwin-amd64.tar.gz`.

**Comment by pvorb** [comment]
Did you configure the `helmDownloadUrl` property of the plugin? It appears to me that you configured it to `https://kubernetes-helm.storage.googleapis.com/`, which leads to the download URL: https://kubernetes-helm.storage.googleapis.com/helm-v3.3.1-darwin-amd64.zip

If you configure `<helmDownloadUrl>https://get.helm.sh/</helmDownloadUrl>` instead or remove the property complete (in order to use the default), the issue should be solved, since on https://get.helm.sh/ ZIP files are available.

Can you please confirm if this workaround works for you?

**Comment by pvorb** [comment]
Since I didn't get any feedback here, I'll close this issue.

Your feedback is still appreciated.
