### ISSUE TITLE
Multiple Maven Helm Plugins

### ISSUE THREAD

**Issue by Vad1mo** [deviceinsight/helm-maven-plugin#75]
I found another similar Maven Plugin that apparently does a similar thing. 

Now I am not sure which one should I choose.  

Is there some sort of comparison regarding this plugin and https://github.com/kiwigrid/helm-maven-plugin?

**Comment by pvorb** [comment]
I've never used the other helm-maven-plugin, but from a quick glance over the README file I'd say that the advantages of the other plugin are

- It's possible to specify separate repositories for uploading staging and release chart versions.
- It has a few more options to configure local helm configuration files.
- It's able to do a dry-run installation from maven.

The plugin you're looking at has the following advantages

- Platform independence. It automatically downloads the correct helm binary for your OS and architecture
- It allows you to test helm templates by rendering them to `target/test-classes`, so you can either inspect the output by hand or you can build unit tests around them.

Both plugins are actively maintained, but the other plugin seems to have more issues. This might be because it is used by more people, but I'm not sure.
